### ISSUE TITLE
Movement part?

### ISSUE THREAD

**Issue by luxuriouscoder26** [LutzGrosshennig/unity3d-AnimatedGridMovement-Camera#4]
Can you please point out the part which actually moves the game object on the grid its difficult to cut out the Animation part.

**Comment by LutzGrosshennig** [comment]
Hey, sure thing! 

Please bear in mind that this script is meant to be a component on your main camera. This way the script has access to the camera transform and can modify it. 

https://github.com/LutzGrosshennig/unity3d-AnimatedGridMovement-Camera/blob/2b50044c49da26c70f93bf798d382b6c5b885b33/AnimatedGridMovement.cs#L86

sets the new position of the camera to a new location between the current position of the camera and the destination position using an offset (step) that is calculated in the caller function (basicaly the gridSize * Time.deltaTime to be FPS independent).

So the animation and the movement (aka setting the new camera position) are tied together. 

You could also use a Vector3.Lerp() instead but then you have to store the original position prior to the transistion as well as an accumulated Time.deltaTime.

Since Vector3.MoveTowards() works incrementaly I used this instead because I found this to be simpler (it boils down to a matter of personal preference, I guess).

Based on how you phrased the question, I have a hunch that this is not quite what you are looking for. 
The script is meant for the camera movement not arbitary game objects.

If you care to explain what you are trying to accomplish I am sure I can give you an better answer.

Regards,
Lutz

**Comment by luxuriouscoder26** [comment]
Well I am making a game about a computer antivirus that destroys corrupted
files on a computer. The idea is simple. Its a small cube which moves in a
grid like movement and can shoot orbs in 4 directions. Like a top-down
shooter in 3d. I have completed the movement and shooting part but not
getting the snappy movement of grid/tile based game. And thanks for the
help.
Regards,
Arkos26

**Comment by LutzGrosshennig** [comment]
The most addictive games are usally the ones based on a 'simple' idea. I stripped down the script to this version which may suits you need a bit better. If you store it as CubeMover.cs and attach it to your cude you should be good to go. You may adjust the gridSize and the speed to your liking. I guess you use own input handling, in this case you should make the four MoveXYZ() methods public so you can access them from your input handler.

```
using UnityEngine;

public class CubeMover : MonoBehaviour
{
    public float gridSize = 4.0f;
    public float speed = 1.0f;

    private Vector3 moveTowardsPosition;

    void Start()
    {
        moveTowardsPosition = transform.position;
    }

    private void FixedUpdate()
    {
        if (!IsMoving())
        {
            if (Input.GetKey(KeyCode.W))
            {
                MoveForward();
            }
            else if (Input.GetKey(KeyCode.S))
            {
                MoveBackward();
            }
            else if (Input.GetKey(KeyCode.A))
            {
                MoveLeft();
            }
            else if (Input.GetKey(KeyCode.D))
            {
                MoveRight();
            }
        }
    }

    void Update()
    {
        if (IsMoving())
        {
            var step = Time.deltaTime * gridSize * speed;
            AnimateMovement(step);
        }
    }

    private void AnimateMovement(float step)
    {
        transform.position = Vector3.MoveTowards(transform.position, moveTowardsPosition, step);
    }

    private bool IsMoving()
    {
        return transform.position != moveTowardsPosition;
    }

    private void MoveForward()
    {
        moveTowardsPosition += CalculateForwardPosition();
    }

    private void MoveBackward()
    {
        moveTowardsPosition += -CalculateForwardPosition();
    }

    private void MoveRight()
    {
        moveTowardsPosition += CalculateRightPosition();
    }

    private void MoveLeft()
    {
        moveTowardsPosition += -CalculateRightPosition();
    }

    private Vector3 CalculateForwardPosition()
    {
        return transform.forward * gridSize;
    }

    private Vector3 CalculateRightPosition()
    {
        return transform.right * gridSize;
    }
}
```

Kind regards,
Lutz

**Comment by luxuriouscoder26** [comment]
Thanks! Man it was really useful. And it works like a charm.

**Comment by luxuriouscoder26** [comment]
I owe for this. If you ever need help, I am here.

**Comment by LutzGrosshennig** [comment]
You are welcome and I am glad I was able to help.

Good luck with your game! And since I am curious now, maybe you can send me some game play footage of it some day.

I am closing the issue now. Feel free to open a new one anytime.

Keep on coding!
Lutz
